// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwijpaDlqo-EE9RT9yRfqQbSsLohdaFDI',
    appId: '1:597397485046:web:57bc7c84eeecda33b283d7',
    messagingSenderId: '597397485046',
    projectId: 'neoshare-e2fa7',
    authDomain: 'neoshare-e2fa7.firebaseapp.com',
    storageBucket: 'neoshare-e2fa7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLbM6SwD_fKVqOLOeuuVnZadPTkKyp-I8',
    appId: '1:597397485046:android:2c7508b9097c4e9db283d7',
    messagingSenderId: '597397485046',
    projectId: 'neoshare-e2fa7',
    storageBucket: 'neoshare-e2fa7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHuu-z013g25XjEQwJBY4DSLZRgJkZLJs',
    appId: '1:597397485046:ios:a61ff411a9ba49c5b283d7',
    messagingSenderId: '597397485046',
    projectId: 'neoshare-e2fa7',
    storageBucket: 'neoshare-e2fa7.firebasestorage.app',
    androidClientId: '597397485046-g1grdicptr1llte452gofvkq5g7qb2j4.apps.googleusercontent.com',
    iosClientId: '597397485046-u9thql6d7h3auj3779jq93c4ea2ac891.apps.googleusercontent.com',
    iosBundleId: 'com.example.sankar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHuu-z013g25XjEQwJBY4DSLZRgJkZLJs',
    appId: '1:597397485046:ios:a61ff411a9ba49c5b283d7',
    messagingSenderId: '597397485046',
    projectId: 'neoshare-e2fa7',
    storageBucket: 'neoshare-e2fa7.firebasestorage.app',
    androidClientId: '597397485046-g1grdicptr1llte452gofvkq5g7qb2j4.apps.googleusercontent.com',
    iosClientId: '597397485046-u9thql6d7h3auj3779jq93c4ea2ac891.apps.googleusercontent.com',
    iosBundleId: 'com.example.sankar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwijpaDlqo-EE9RT9yRfqQbSsLohdaFDI',
    appId: '1:597397485046:web:f75888fdcb94354eb283d7',
    messagingSenderId: '597397485046',
    projectId: 'neoshare-e2fa7',
    authDomain: 'neoshare-e2fa7.firebaseapp.com',
    storageBucket: 'neoshare-e2fa7.firebasestorage.app',
  );
}
